FROM ruby:3.2.5
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 0xB1998361219BD9C9 && \
  echo "deb http://repos.azulsystems.com/debian stable main" | tee /etc/apt/sources.list.d/zulu.list && \
  apt-get update -qq && \
  apt-get install -y curl git build-essential libpq-dev nodejs libpq-dev postgresql-client zip zulu-8 \
  --fix-missing \
  --no-install-recommends && \
  gem update bundler

# Set up the shell RC file
COPY export-root-env.sh .env /root/
RUN chmod +x /root/export-root-env.sh &&  echo "source /root/export-root-env.sh" >> /root/.bashrc

# Install some additional files
WORKDIR /aprexis
COPY wait-for-it.sh setup-for-rails.sh ./

# Disable IPV6
RUN cp /etc/hosts /tmp/hosts.original && sed -e 's/localhost ip6-localhost/ip6-localhost/' /tmp/hosts.original >/tmp/hosts

WORKDIR /aprexis-engine
RUN mkdir -p /aprexis-engine/lib/aprexis/engine
COPY ./aprexis-engine/lib/aprexis/engine/version.rb /aprexis-engine/lib/aprexis/engine
COPY ./aprexis-engine/Gemfile ./aprexis-engine/aprexis-engine.gemspec ./aprexis-engine/Gemfile.lock ./
RUN bundle install

# Install the application
ADD ./aprexis-engine /aprexis-engine
