FROM ruby:3.0.3
COPY ./aprexis-etl/Gemfile.lock /tmp/Gemfile.lock.tmp
RUN apt-get update -qq && \
  apt-get install -y curl \
  git \
  build-essential \
  libpq-dev \
  nodejs \
  libpq-dev \
  postgresql-client \
  zip \
  --fix-missing \
  --no-install-recommends && \
  gem install bundler -v $(grep 'BUNDLED WITH' -A1 /tmp/Gemfile.lock.tmp | tail -n 1 )

RUN echo "export SCRIPT_ENV=development" >> /root/.bashrc

WORKDIR /aprexis-etl
COPY ./aprexis-etl/Gemfile ./aprexis-etl/Gemfile.lock ./

# Install the application
ADD ./aprexis-etl /aprexis-etl
