FROM ruby:3.0.3
RUN apt-get update -qq && \
    apt-get install -y curl git build-essential libpq-dev nodejs libpq-dev postgresql-client \
    --fix-missing \
    --no-install-recommends && \
    gem update bundler

# Set up the shell RC file
COPY .env export-root-env.sh /root/
RUN chmod +x /root/export-root-env.sh &&  echo "source /root/export-root-env.sh" >> /root/.bashrc

# Install some additional files
WORKDIR /aprexis
COPY wait-for-it.sh setup-for-rails.sh ./

# Install aprexis-engine (uncomment if using local repository)
WORKDIR /aprexis-engine
ADD ./aprexis-engine /aprexis-engine

# Disable IPV6
RUN cp /etc/hosts /tmp/hosts.original && sed -e 's/localhost ip6-localhost/ip6-localhost/' /tmp/hosts.original >/tmp/hosts

WORKDIR /aprexis-api
COPY ./aprexis-api/Gemfile ./aprexis-api/Gemfile.lock ./
RUN export $(grep -v '^[[:space:]]*#' /root/.env | xargs) && bundle config --local GITHUB__COM x-access-token:${APREXIS_ENGINE_TOKEN} && bundle install

# Install the application
ADD ./aprexis-api /aprexis-api
ADD ./aprexis-platform-5/storage /aprexis-api/storage
