version: '2.2'

services:
  postgres:
    image: postgres:13.4
    shm_size: 1g
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    ports:
      - "${APREXIS_POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "${APREXIS_REDIS_PORT}:6379"
    volumes:
      - redis_data:/var/lib/redis/data

  engine:
    build:
      context: .
      dockerfile: Dockerfile-engine
    image: aprexis/aprexis-engine:latest
    links:
      - postgres
      - redis
    volumes:
      - ./aprexis-engine:/aprexis-engine
    command: bash

volumes:
  postgres_data:
  redis_data:
