version: '2.2'

services:
  postgres:
    image: postgres:13.4
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    ports:
      - "${APREXIS_POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "${APREXIS_REDIS_PORT}:6379"
    volumes:
      - redis_data:/var/lib/redis/data

  solr:
    build:
      context: .
      dockerfile: Dockerfile-platform
    image: aprexis/aprexis-platform-5:latest
    ports:
      - "${APREXIS_SOLR_PORT}:8983"
    volumes:
      - ./aprexis-platform-5:/aprexis-platform-5
    command: bash --login -c "/aprexis/setup-for-rails.sh; rm -f tmp/pids/server.pid && bundle exec rails sunspot:solr:run"

  engine:
    build:
      context: .
      dockerfile: Dockerfile-engine
    image: aprexis/aprexis-engine:latest
    links:
      - postgres
      - redis
      - solr
    volumes:
      - ./aprexis-engine:/aprexis-engine
    command: bash

  platform:
    image: aprexis/aprexis-platform-5:latest
    links:
      - postgres
      - redis
      - solr
    volumes:
      - ./aprexis-platform-5:/aprexis-platform-5
    command: bash --login -c "/aprexis/setup-for-platform.sh; rm -f tmp/pids/server.pid && bundle exec puma -b tcp://0.0.0.0:3000"
    ports:
      - "${APREXIS_PLATFORM_PORT}:3000"

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    image: aprexis/aprexis-api:latest
    links:
      - postgres
      - redis
      - solr
    volumes:
      - ./aprexis-api:/aprexis-api
      - ./aprexis-platform-5/storage:/aprexis-api/storage
    command: bash --login -c "/aprexis/setup-for-rails.sh; rm -f tmp/pids/server.pid && bundle exec puma -b tcp://0.0.0.0:3250"
    ports:
      - "${APREXIS_API_PORT}:3250"

  ui:
    image: node:14.16.0
    ports:
      - "${APREXIS_API_UI_PORT}:3500"
    environment:
      - NODE_ENV=development
      - PORT=3500
      - REACT_APP_APREXIS_API=http://localhost:${APREXIS_API_PORT}
    links:
      - api
    volumes:
      - ./aprexis-api-ui:/app
    working_dir: /app
    command: "bash --login -c 'yarn install; yarn start-docker'"
    depends_on:
      - api

  resque-worker:
    image: aprexis/aprexis-platform-5:latest
    links:
      - postgres
      - redis
      - solr
    volumes:
      - ./aprexis-platform-5:/aprexis-platform-5
    command: bash --login -c "/aprexis/setup-for-platform.sh; bundle exec rails resque:work QUEUE=*"
    ports: []

  resque-scheduler:
    image: aprexis/aprexis-platform-5:latest
    links:
      - postgres
      - redis
      - solr
    volumes:
      - ./aprexis-platform-5:/aprexis-platform-5
    command: bash --login -c "/aprexis/setup-for-platform.sh; bundle exec rails resque:scheduler"
    ports: []

volumes:
  postgres_data:
  redis_data:
