FROM ruby:3.0.3
COPY ./aprexis-engine/Gemfile.lock /tmp/Gemfile.lock.tmp
RUN apt-get update -qq && \
  apt-get install -y curl git build-essential libpq-dev nodejs libpq-dev postgresql-client zip \
  --fix-missing \
  --no-install-recommends && \
  gem install bundler -v $(grep 'BUNDLED WITH' -A1 /tmp/Gemfile.lock.tmp | tail -n 1 )

# Install some additional files
WORKDIR /aprexis

# Disable IPV6
RUN cp /etc/hosts /tmp/hosts.original && sed -e 's/localhost ip6-localhost/ip6-localhost/' /tmp/hosts.original >/tmp/hosts

WORKDIR /aprexis-engine
RUN mkdir -p /aprexis-engine/lib/aprexis/engine
COPY ./aprexis-engine/lib/aprexis/engine/version.rb /aprexis-engine/lib/aprexis/engine
COPY ./aprexis-engine/Gemfile ./aprexis-engine/aprexis-engine.gemspec ./aprexis-engine/Gemfile.lock ./

# Install the application
ADD ./aprexis-engine /aprexis-engine
