FROM ruby:3.0.3

COPY ./aprexis-api/Gemfile.lock /tmp/Gemfile.lock.tmp
RUN apt-get update -qq && \
    apt-get install -y curl git build-essential libpq-dev nodejs postgresql-client \
    --fix-missing \
    --no-install-recommends && \
    gem install bundler -v $(grep 'BUNDLED WITH' -A1 /tmp/Gemfile.lock.tmp | tail -n 1 )

# Install some additional files
WORKDIR /aprexis

# Install aprexis-engine (uncomment if using local repository)
WORKDIR /aprexis-engine
ADD ./aprexis-engine /aprexis-engine

# Disable IPV6
RUN cp /etc/hosts /tmp/hosts.original && sed -e 's/localhost ip6-localhost/ip6-localhost/' /tmp/hosts.original >/tmp/hosts

WORKDIR /aprexis-api
COPY ./aprexis-api/Gemfile ./aprexis-api/Gemfile.lock ./

# Install the application
ADD ./aprexis-api /aprexis-api
ADD ./aprexis-platform-5/storage /aprexis-api/storage
